from __future__ import annotations

from collections import OrderedDict

APP_NAME = "Open Health Agent"
APP_VERSION = "0.1.0"
DEFAULT_HOME_NAME = ".open-health-agent"
DEFAULT_LOOKBACK_DAYS = 14
DEFAULT_BACKUP_RETENTION = 14
DEFAULT_PLANNING_TEF_FRACTION = 0.10
FORMULA_ID = "cunningham_1991_ffm"

SHEET_HEADERS: OrderedDict[str, list[str]] = OrderedDict(
    {
        "健康日报": [
            "日期",
            "步数",
            "距离_km",
            "活跃消耗_kcal",
            "活跃分钟",
            "睡眠开始",
            "睡眠结束",
            "实际睡眠时长_h",
            "深睡_min",
            "核心/浅睡_min",
            "REM_min",
            "清醒_min",
            "静息心率_bpm",
            "HRV_ms",
            "血氧_%",
            "呼吸率_次/分",
            "VO2max",
            "体重_kg",
            "体脂率_%",
            "身高_cm",
            "睡眠来源",
            "健康数据来源",
            "数据截止时间",
            "数据质量",
            "导入批次ID",
            "导入时间",
            "备注",
        ],
        "健康测量": [
            "记录ID",
            "日期",
            "时间",
            "指标",
            "数值",
            "第二数值",
            "单位",
            "来源",
            "记录方式",
            "置信度",
            "原话",
            "备注",
            "导入时间",
        ],
        "训练记录": [
            "记录ID",
            "日期",
            "开始时间",
            "训练类型",
            "时长_min",
            "距离_km",
            "热量_kcal",
            "平均心率_bpm",
            "最大心率_bpm",
            "强度/RPE",
            "训练肌群",
            "训练来源",
            "外部ID",
            "记录方式",
            "置信度",
            "原话",
            "备注",
            "导入时间",
        ],
        "饮食记录": [
            "记录ID",
            "日期",
            "时间",
            "餐次",
            "食物",
            "食用量估计_g",
            "食用量下限_g",
            "食用量上限_g",
            "热量_kcal",
            "蛋白质_g",
            "脂肪_g",
            "饱和脂肪_g",
            "碳水_g",
            "膳食纤维_g",
            "糖_g",
            "酒精_g",
            "钠_mg",
            "钾_mg",
            "钙_mg",
            "铁_mg",
            "镁_mg",
            "磷_mg",
            "锌_mg",
            "维生素A_ug_RAE",
            "维生素C_mg",
            "维生素D_ug",
            "维生素E_mg",
            "维生素B1_mg",
            "维生素B2_mg",
            "叶酸_ug_DFE",
            "维生素B12_ug",
            "胆固醇_mg",
            "咖啡因_mg",
            "数据来源",
            "估算说明",
            "置信度",
            "图片引用",
            "原话",
            "备注",
            "录入时间",
        ],
        "饮食营养明细": [
            "记录ID",
            "营养素ID",
            "营养素",
            "数值",
            "单位",
            "数据来源",
            "每100g或每份",
            "检索日期",
            "备注",
        ],
        "每日营养汇总": [
            "日期",
            "已记录条目数",
            "已记录热量_kcal",
            "蛋白质_g",
            "脂肪_g",
            "碳水_g",
            "膳食纤维_g",
            "糖_g",
            "钠_mg",
            "钾_mg",
            "钙_mg",
            "铁_mg",
            "镁_mg",
            "估算TEF下限_kcal",
            "估算TEF中值_kcal",
            "估算TEF上限_kcal",
            "记录覆盖说明",
            "更新时间",
        ],
        "目标历史": [
            "目标ID",
            "生效日期",
            "状态",
            "优先级",
            "用户原话",
            "安全约束",
            "记录时间",
        ],
        "可穿戴数据覆盖": [
            "数据类型",
            "读取方式",
            "数据粒度",
            "本次读取状态",
            "累计记录数",
            "最早日期",
            "最晚日期",
            "最新数据时间",
            "来源数",
            "最近检查时间",
            "失败查询数",
            "使用边界",
        ],
        "同步日志": [
            "批次ID",
            "运行时间",
            "查询起始日期",
            "查询结束日期",
            "日报记录数",
            "训练记录数",
            "测量记录数",
            "状态",
            "数据截止时间",
            "错误摘要",
        ],
        "健康说明": ["项目", "说明"],
    }
)

HEALTH_SHEETS = tuple(SHEET_HEADERS)

DAILY_FIELD_MAP = {
    "date": "日期",
    "steps": "步数",
    "distance_km": "距离_km",
    "active_energy_kcal": "活跃消耗_kcal",
    "active_minutes": "活跃分钟",
    "sleep_start": "睡眠开始",
    "sleep_end": "睡眠结束",
    "sleep_hours": "实际睡眠时长_h",
    "deep_minutes": "深睡_min",
    "light_minutes": "核心/浅睡_min",
    "rem_minutes": "REM_min",
    "awake_minutes": "清醒_min",
    "resting_heart_rate_bpm": "静息心率_bpm",
    "hrv_ms": "HRV_ms",
    "spo2_percent": "血氧_%",
    "respiratory_rate": "呼吸率_次/分",
    "vo2max": "VO2max",
    "weight_kg": "体重_kg",
    "body_fat_percent": "体脂率_%",
    "height_cm": "身高_cm",
    "sleep_source": "睡眠来源",
    "sources": "健康数据来源",
    "data_until": "数据截止时间",
    "quality": "数据质量",
    "batch_id": "导入批次ID",
    "imported_at": "导入时间",
    "notes": "备注",
}

SUMMARY_NUTRIENT_FIELDS = {
    "energy_kcal": "热量_kcal",
    "protein_g": "蛋白质_g",
    "fat_g": "脂肪_g",
    "saturated_fat_g": "饱和脂肪_g",
    "carbohydrate_g": "碳水_g",
    "fiber_g": "膳食纤维_g",
    "sugar_g": "糖_g",
    "alcohol_g": "酒精_g",
    "sodium_mg": "钠_mg",
    "potassium_mg": "钾_mg",
    "calcium_mg": "钙_mg",
    "iron_mg": "铁_mg",
    "magnesium_mg": "镁_mg",
    "phosphorus_mg": "磷_mg",
    "zinc_mg": "锌_mg",
    "vitamin_a_ug_rae": "维生素A_ug_RAE",
    "vitamin_c_mg": "维生素C_mg",
    "vitamin_d_ug": "维生素D_ug",
    "vitamin_e_mg": "维生素E_mg",
    "thiamin_mg": "维生素B1_mg",
    "riboflavin_mg": "维生素B2_mg",
    "folate_ug_dfe": "叶酸_ug_DFE",
    "vitamin_b12_ug": "维生素B12_ug",
    "cholesterol_mg": "胆固醇_mg",
    "caffeine_mg": "咖啡因_mg",
}

HEALTH_NOTES = [
    ("定位", "个人 wellness/fitness 记录与趋势工具，不是医疗器械、诊断、处方或急救监测服务。"),
    ("数据真源", "本地 SQLite 用于幂等写入和审计；Excel 是用户持有、便于查看和跨设备同步的可读导出视图。受管工作表会在导出时重建；自定义内容请放独立工作表。"),
    ("缺失值", "空白表示当前没有可验证数据；绝不把同步缺失、授权失败或未佩戴写成 0。"),
    ("日期口径", "睡眠按醒来/结束日期归档；当天数据在本地日结束前均为不完整的截至目前数据。"),
    ("睡眠时长", "实际睡眠时长按 asleep 口径计算，不含清醒分钟；睡眠窗口可由开始和结束时间另行判断。"),
    ("设备来源", "来源字段只能说明数据链路，不能仅凭来源名称断言具体设备型号。"),
    ("可穿戴分层", "ghealth 支持的数据类型进入 SQLite 原始采集层；Excel 仅展示逐类型覆盖摘要。细粒度样本、ECG 波形和厂商原始字段不会自动进入 Agent 决策上下文，只有经过明确语义映射和规则校验的字段才用于分析。"),
    ("食物照片", "图片营养为估算；保存食物识别、份量区间、来源和不确定性。用户纠正时更新原记录，不追加矛盾副本。"),
    ("热量模型", "估算静息能量使用 370 + 21.6 × 瘦体重(kg)；综合热量仅在活动字段为 active energy 时加活动与 TEF，避免重复计算。"),
    ("隐私", "设备厂商、Apple/Google 健康数据层、模型或语音/视觉服务、微信/腾讯、Google 与 iCloud 可能处理相应数据；凭据、照片、目标和真实健康档案不得提交到 Git。"),
]
